---
title: "Untitled"
author: "Zachary M. Smith"
date: "4/24/2019"
output: html_document
---

# BAP Plots

Brian Duffy requested...
*"Boxplot BAP with LogTP (avg or scatter) -highlight mainstem"*

## Preprocess
```{r}
final.df <- bap.df %>% 
    select(station,
         location,
         rivmile,
         date,
         bap) %>% 
  full_join(tp.df, by = "station") %>% 
  full_join(station_order.df, by = "station") %>% 
  arrange(order) %>% 
  mutate(station = factor(station, unique(station)))
```

## Boxplot

```{r}
final.df %>% 
  ggplot(aes(station, bap)) +
  geom_boxplot() +
  geom_point(aes(y = tp_log10 * 2), color = "red") +
  xlab("Station") +
  ylab("BAP") +
  scale_y_continuous(sec.axis = sec_axis(~. / 2, name = "Log10 TP")) +
  theme(axis.text.x = element_text(angle = 90,
                                   hjust = 1,
                                   vjust = 0.5))
```

## Scatter Plot

```{r}
final.df %>% 
  mutate(wallkill = if_else(location == "WALK", "Wallkill", "Tributary")) %>% 
  ggplot(aes(tp_log10, bap, color = wallkill)) +
  geom_point() +
  xlab("Log10 TP") +
  ylab("BAP") 
```
